# TỔ CHỨC LẠI DỮ LIỆU

In [1]:
import pandas as pd

In [23]:
url=r'A:\UET-VNU\project\covid19_data.csv' # thay đổi đường dẫn tuyệt đối khi chạy
df=pd.read_csv(url)

In [8]:
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429430,ZWE,Africa,Zimbabwe,2024-07-31,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
429431,ZWE,Africa,Zimbabwe,2024-08-01,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
429432,ZWE,Africa,Zimbabwe,2024-08-02,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
429433,ZWE,Africa,Zimbabwe,2024-08-03,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
429434,ZWE,Africa,Zimbabwe,2024-08-04,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN

## Điền dữ liệu cho các cột liên quan đến tiêm chủng giá trị 0 từ trước '08/12/2020

In [9]:

df['date'] = pd.to_datetime(df['date'])
filtered_df = df[df['date'] < pd.to_datetime('2020-12-08')]
columns_to_fill = ['total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed', 'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred', 
                    'new_vaccinations_smoothed_per_million', 'new_people_vaccinated_smoothed', 'new_people_vaccinated_smoothed_per_hundred']
filtered_df[columns_to_fill] = filtered_df[columns_to_fill].fillna(0)
df.update(filtered_df)

C:\Users\FPT\AppData\Local\Temp\ipykernel_13540\2908275457.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[columns_to_fill] = filtered_df[columns_to_fill].fillna(0)

In [10]:
# Kiểm tra tỷ lệ dữ liệu thiếu
missing_data = df.isnull().mean() * 100

miss = 75
columns_to_drop = missing_data[missing_data > miss].index
df = df.drop(columns=columns_to_drop)

print(f"Các cột đã bị loại bỏ: {columns_to_drop}")
missing_data

Các cột đã bị loại bỏ: Index(['icu_patients', 'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

iso_code                                    0.000000
continent                                   6.176721
location                                    0.000000
date                                        0.000000
total_cases                                 4.105627
                                             ...
population                                  0.000000
excess_mortality_cumulative_absolute       96.877059
excess_mortality_cumulative                96.877059
excess_mortality                           96.877059
excess_mortality_cumulative_per_million    96.877059
Length: 67, dtype: float64

# Giữ lại các cột có ý nghĩa cần phân tích

In [ ]:


# Danh sách các cột mong muốn dữ lại
columns_to_select = ['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed',
                       'total_deaths', 'new_deaths', 'new_deaths', 'total_cases_per_million', 'new_cases_per_million',
                       'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million',
                       'new_deaths_smoothed_per_million', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated',
                       'new_vaccinations', 'new_vaccinations_smoothed', 'total_vaccinations_per_hundred',
                       'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred', 'new_people_vaccinated_smoothed',
                       'new_people_vaccinated_smoothed_per_hundred', 'hospital_beds_per_thousand']

selected_df = df[columns_to_select]

# Chia nhỏ dữ liệu thành các tệp con để xử lý cho phù hợp

In [ ]:
world_data=selected_df[selected_df['location']=='World']
countries_df = selected_df[~selected_df['location'].isin([
    'World',
    'Asia', 'Europe', 'Africa', 'Oceania', 'North America', 'South America',
    'European Union (27)',
    'High-income countries',
    'Upper-middle-income countries',
    'Lower-middle-income countries',
    'Low-income countries'
])]
income_groups = ['High-income countries', 'Upper-middle-income countries', 'Lower-middle-income countries', 'Low-income countries']
income_data=selected_df[selected_df['location'].isin(income_groups)]
contiment=['Asia', 'Europe', 'Africa', 'Oceania', 'North America', 'South America']
contiment_data = selected_df[(selected_df['location'].isin(contiment)) & (selected_df['continent'].isnull())]
contiment_data

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths,...,people_vaccinated,people_fully_vaccinated,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,hospital_beds_per_thousand
1674,OWID_AFR,NaN,Africa,2020-01-05,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1675,OWID_AFR,NaN,Africa,2020-01-06,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1676,OWID_AFR,NaN,Africa,2020-01-07,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1677,OWID_AFR,NaN,Africa,2020-01-08,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1678,OWID_AFR,NaN,Africa,2020-01-09,0.0,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359233,OWID_SAM,NaN,South America,2024-07-31,68808110.0,0.0,205.714,1354186.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359234,OWID_SAM,NaN,South America,2024-08-01,68808110.0,0.0,205.714,1354186.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359235,OWID_SAM,NaN,South America,2024-08-02,68808110.0,0.0,205.714,1354186.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359236,OWID_SAM,NaN,South America,2024-08-03,68808110.0,0.0,205.714,1354186.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359237,OWID_SAM,NaN,South America,2024-08-04,68809418.0,1308.0,186.857,1354187.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
world_data.to_csv('world_data.csv')
countries_df.to_csv('contries_data.csv')
income_data.to_csv('income_data.csv')
contiment_data.to_csv('contimets_data.csv')